### ISSUE TITLE
release 3.0.0

### ISSUE THREAD

**Issue by craue** [craue/CraueFormFlowBundle#105]
## new features
- [x] #98+#143: add a validation error to the current form if a form of a previous step became invalid
- [x] #101: support for concurrent instances of the same flow
- [x] #122: add support for PUT method
- [x] #125: add generic form options to simplify passing options to all steps
- [x] #126: allow custom classes on buttons
- [x] #142: redirect after submit
- [x] #146: handling of file uploads
- [x] #148: restructure data storage
- [x] #175+#178: form options for each step
- [x] #196: allow to use a closure for the `validation_groups` option
- [x] #215: add a default `getName` implementation
- [x] #217: add DoctrineStorage to store data in a Doctrine-managed database
- [x] #219+#238: allow a callable for each step label
- [x] #220: add expired form detection
- [x] #226: allow custom button labels
- [x] #262: added getters for steps remaining and done
- [x] #280: added an option for removing the reset button

## improvements
- [x] #104: remove options from method `createForm`
- [x] #117: let `getFormOptions` return an array for the `validation_groups` option
- [x] #180: rename step config option `type` to `form_type`
- [x] #184: make the bundle Symfony 3 compatible, bump Symfony dependency to 2.6

## l10n
- [x] #107: add Czech translation
- [x] #112: improve Dutch translation
- [x] #133+#134: add Farsi translation
- [x] #254: add Slovak translation
- [x] #293: add Hungarian translation

## cleanup
- [x] #145: bump Symfony dependency to 2.3
- [x] #222: bump Symfony dependency to 2.7
- [x] b6ac40243b0ed8f15e055aafc8c3d5cad46f225c: remove the deprecated step field template
- [x] 9059c38570fc5793cc154141cd8b193e347c32c1: rename property `step` to `stepNumber` and method `getStep` to `getStepNumber` within event classes
- [x] 2e2c90050e38d9dbe552f11e40729f6a65ecb2ea: use PSR-4 instead of PSR-0
